/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#171c3c';
const tintColorDark = '#dee1ff';

export const Colors = {
  light: {
    text: '#171c2f',
    background: '#f7f8fc',
    tint: '#283058',
    icon: '#48506a',
    tabIconDefault: '#6f7690',
    tabIconSelected: tintColorLight,
    primary: '#283058',
    onPrimary: '#ffffff',
    primaryContainer: '#dfe3ff',
    onPrimaryContainer: '#121938',
    secondary: '#4d5679',
    onSecondary: '#ffffff',
    secondaryContainer: '#dfe3ff',
    onSecondaryContainer: '#18203f',
    surface: '#fdfbff',
    onSurface: '#171c2f',
    surfaceVariant: '#e1e5f0',
    onSurfaceVariant: '#434b63',
    outline: '#68708a',
    outlineVariant: '#c4cad9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f5fb',
    surfaceContainer: '#edf0f7',
    surfaceContainerHigh: '#e7ebf3',
    surfaceContainerHighest: '#e0e5ee',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
  },
  dark: {
    text: '#efeff5',
    background: '#0c0c0e',
    tint: tintColorDark,
    icon: '#c8c6cf',
    tabIconDefault: '#94909a',
    tabIconSelected: tintColorDark,
    primary: '#c4c8f5',
    onPrimary: '#2e304f',
    primaryContainer: '#404566',
    onPrimaryContainer: '#e0e1ff',
    secondary: '#c0c5ef',
    onSecondary: '#292f54',
    secondaryContainer: '#3e446c',
    onSecondaryContainer: '#e0e1ff',
    surface: '#18171c',
    onSurface: '#e6e1e5',
    surfaceVariant: '#46464d',
    onSurfaceVariant: '#c8c6cf',
    outline: '#92909a',
    outlineVariant: '#46464d',
    surfaceContainerLowest: '#0d0c0f',
    surfaceContainerLow: '#1c1b1f',
    surfaceContainer: '#201f23',
    surfaceContainerHigh: '#2a292e',
    surfaceContainerHighest: '#353439',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
  },
};
