/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#171c3c';
const tintColorDark = '#dee1ff';

export const Colors = {
  light: {
    text: '#1b1b1e',
    background: '#fcf8fb',
    tint: tintColorLight,
    icon: '#46464d',
    tabIconDefault: '#77767e',
    tabIconSelected: tintColorLight,
    primary: '#171c3c',
    onPrimary: '#ffffff',
    primaryContainer: '#2d3252',
    onPrimaryContainer: '#959ac1',
    secondary: '#555c84',
    onSecondary: '#ffffff',
    secondaryContainer: '#c8cffe',
    onSecondaryContainer: '#50577f',
    surface: '#fcf8fb',
    onSurface: '#1b1b1e',
    surfaceVariant: '#e5e1e4',
    onSurfaceVariant: '#46464d',
    outline: '#77767e',
    outlineVariant: '#c7c5ce',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f6f3f6',
    surfaceContainer: '#f0edf0',
    surfaceContainerHigh: '#eae7ea',
    surfaceContainerHighest: '#e5e1e4',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
  },
  dark: {
    text: '#efeff5',
    background: '#0c0c0e',
    tint: tintColorDark,
    icon: '#c8c6cf',
    tabIconDefault: '#94909a',
    tabIconSelected: tintColorDark,
    primary: '#c4c8f5',
    onPrimary: '#2e304f',
    primaryContainer: '#404566',
    onPrimaryContainer: '#e0e1ff',
    secondary: '#c0c5ef',
    onSecondary: '#292f54',
    secondaryContainer: '#3e446c',
    onSecondaryContainer: '#e0e1ff',
    surface: '#18171c',
    onSurface: '#e6e1e5',
    surfaceVariant: '#46464d',
    onSurfaceVariant: '#c8c6cf',
    outline: '#92909a',
    outlineVariant: '#46464d',
    surfaceContainerLowest: '#0d0c0f',
    surfaceContainerLow: '#1c1b1f',
    surfaceContainer: '#201f23',
    surfaceContainerHigh: '#2a292e',
    surfaceContainerHighest: '#353439',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
  },
};

